import { memo, type ReactNode } from "react";
import { Pressable, StyleSheet, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { AppText } from "@/components/AppText";
import { BrandLogo } from "@/components/BrandLogo";
import { Card, Divider, IconButton, Skeleton, StatusBadge } from "@/components/ui";
import { useTheme } from "@/theme";
import { formatDateTime, formatINR, formatQuantity } from "@/utils/formatters";
import { orderStatusPresentation } from "./presentation";
import type { DashboardOrder, DashboardStats, LowStockProduct } from "./types";

export function DashboardHeader({ username, unreadCount, onNotifications, onProfile }: { username: string; unreadCount?: number; onNotifications: () => void; onProfile: () => void }) { const t = useTheme(); const hour = new Date().getHours(); const greeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening"; return <View style={s.header}><BrandLogo size={48} compact /><View style={s.flex}><AppText role="caption" style={{ color: t.colors.textSecondary }}>Sushant Control</AppText><AppText role="sectionTitle" numberOfLines={1}>{greeting}, {username}</AppText><AppText role="caption" style={{ color: t.colors.textMuted }}>Business overview</AppText></View><View><IconButton icon="notifications-outline" label={unreadCount ? `${unreadCount} unread notifications` : "Notifications"} onPress={onNotifications} />{!!unreadCount && <View accessibilityElementsHidden style={[s.badgeCount, { backgroundColor: t.colors.danger }]}><AppText role="status" style={{ color: t.colors.textInverse }}>{unreadCount > 99 ? "99+" : unreadCount}</AppText></View>}</View><IconButton icon="person-circle-outline" label="Account and sign out" onPress={onProfile} /></View>; }

export function FinancialHero({ stats }: { stats: DashboardStats }) { const t = useTheme(); return <Card style={[s.hero, { backgroundColor: t.colors.brandSoft, borderColor: t.colors.brand }]}><View style={s.heroTitle}><View style={[s.heroIcon, { backgroundColor: t.colors.brand }]}><Ionicons name="trending-up" size={22} color={t.colors.brandForeground} /></View><View style={s.flex}><AppText role="overline" style={{ color: t.colors.brand }}>RECORDED SALES VALUE</AppText><AppText role="caption" style={{ color: t.colors.textSecondary }}>Non-cancelled order subtotals</AppText></View></View><AppText accessibilityLabel={`Recorded sales value ${formatINR(stats.totalRevenue)}`} role="financialHero" adjustsFontSizeToFit numberOfLines={1} style={{ color: t.colors.brand }}>{formatINR(stats.totalRevenue)}</AppText><Divider /><View style={s.heroSupport}><HeroValue label="Collected" value={formatINR(stats.totalCollected)} /><HeroValue label="Outstanding" value={formatINR(stats.totalDue)} /><HeroValue label="Orders" value={String(stats.totalOrders)} /></View></Card>; }
function HeroValue({ label, value }: { label: string; value: string }) { const t = useTheme(); return <View style={s.heroValue}><AppText role="caption" style={{ color: t.colors.textMuted }}>{label}</AppText><AppText role="financialCompact" adjustsFontSizeToFit numberOfLines={1}>{value}</AppText></View>; }

export function DashboardMetricGrid({ stats, cardWidth }: { stats: DashboardStats; cardWidth: number }) { return <View style={s.grid}><DashboardMetric icon="time-outline" label="Pending orders" value={String(stats.pendingOrders)} tone="warning" width={cardWidth} /><DashboardMetric icon="cube-outline" label="Active products" value={String(stats.activeProducts)} tone="brand" width={cardWidth} /><DashboardMetric icon="wallet-outline" label="Total due" value={formatINR(stats.totalDue)} tone="danger" width={cardWidth} /><DashboardMetric icon="warning-outline" label="Low-stock preview" value={String(stats.lowStockCount)} context={`Up to 10 · threshold ${stats.lowStockThreshold}`} tone="warning" width={cardWidth} /></View>; }
const DashboardMetric = memo(function DashboardMetric({ icon, label, value, context, tone, width }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string; context?: string; tone: "brand" | "warning" | "danger"; width: number }) { const t = useTheme(); const color = tone === "warning" ? t.colors.warning : tone === "danger" ? t.colors.danger : t.colors.brand; const soft = tone === "warning" ? t.colors.warningSoft : tone === "danger" ? t.colors.dangerSoft : t.colors.brandSoft; return <Card style={{ width, gap: t.spacing.sm }}><View style={[s.metricIcon, { backgroundColor: soft }]}><Ionicons name={icon} size={20} color={color} /></View><AppText role="financialValue" adjustsFontSizeToFit numberOfLines={1}>{value}</AppText><AppText role="label" style={{ color: t.colors.textSecondary }}>{label}</AppText>{context && <AppText role="caption" style={{ color: t.colors.textMuted }}>{context}</AppText>}</Card>; });

export function DashboardSection({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { const t = useTheme(); return <Card style={{ gap: t.spacing.sm }}><View style={s.sectionTitle}><AppText role="cardTitle" style={s.flex}>{title}</AppText>{action}</View>{children}</Card>; }
export const RecentOrderRow = memo(function RecentOrderRow({ order, last }: { order: DashboardOrder; last?: boolean }) { const t = useTheme(); const status = orderStatusPresentation(order.status); return <View><View style={s.dataRow}><View style={s.flex}><AppText role="bodyStrong" numberOfLines={1}>{order.orderNumber}</AppText><AppText role="caption" numberOfLines={1} style={{ color: t.colors.textSecondary }}>{order.customerName}</AppText><AppText role="caption" style={{ color: t.colors.textMuted }}>{formatDateTime(order.createdAt)}</AppText></View><View style={s.rowEnd}><AppText role="financialCompact" numberOfLines={1}>{formatINR(order.subtotal)}</AppText><StatusBadge label={status.label} tone={status.tone} icon={status.icon} /></View></View>{!last && <Divider />}</View>; });
export const LowStockRow = memo(function LowStockRow({ product, last }: { product: LowStockProduct; last?: boolean }) { const t = useTheme(); const out = product.stock <= 0; return <View><View style={s.dataRow}><View style={[s.metricIcon, { backgroundColor: out ? t.colors.dangerSoft : t.colors.warningSoft }]}><Ionicons name={out ? "close-circle-outline" : "warning-outline"} size={20} color={out ? t.colors.danger : t.colors.warning} /></View><View style={s.flex}><AppText role="bodyStrong" numberOfLines={1}>{product.name}</AppText><AppText role="caption" style={{ color: t.colors.textSecondary }}>{formatQuantity(product.stock, product.unit)}</AppText></View><StatusBadge label={out ? "Out" : "Low"} tone={out ? "danger" : "warning"} icon={out ? "close-circle-outline" : "warning-outline"} /></View>{!last && <Divider />}</View>; });
export function TextAction({ label, onPress }: { label: string; onPress: () => void }) { const t = useTheme(); return <Pressable accessibilityRole="button" onPress={onPress} hitSlop={8} style={({ pressed }) => ({ opacity: pressed ? .6 : 1, padding: 4 })}><AppText role="label" style={{ color: t.colors.brand }}>{label}</AppText></Pressable>; }
export function OfflineBanner({ message = "Offline · showing last loaded data" }: { message?: string }) { const t = useTheme(); return <View accessibilityRole="alert" style={[s.offline, { backgroundColor: t.colors.warningSoft, borderColor: t.colors.warning }]}><Ionicons name="cloud-offline-outline" size={18} color={t.colors.warning} /><AppText role="caption" style={{ color: t.colors.warning, flex: 1 }}>{message}</AppText></View>; }
export function DashboardSkeleton({ cardWidth }: { cardWidth: number }) { const t = useTheme(); return <View style={{ gap: t.spacing.xl }}><View style={s.header}><Skeleton width={48} height={48} radius={14} /><View style={[s.flex, { gap: 6 }]}><Skeleton width="38%" height={12} /><Skeleton width="72%" height={22} /><Skeleton width="45%" height={12} /></View></View><Card style={{ gap: t.spacing.md }}><Skeleton width="45%" /><Skeleton width="78%" height={38} /><Divider /><View style={s.heroSupport}><Skeleton width="28%" height={34} /><Skeleton width="28%" height={34} /><Skeleton width="28%" height={34} /></View></Card><View style={s.grid}>{[0,1,2,3].map(i => <Card key={i} style={{ width: cardWidth, gap: 9 }}><Skeleton width={36} height={36} radius={12} /><Skeleton width="66%" height={24} /><Skeleton width="82%" /></Card>)}</View><Card style={{ gap: 14 }}><Skeleton width="38%" height={20} />{[0,1,2].map(i => <View key={i} style={{ gap: 8 }}><Skeleton width="55%" /><Skeleton width="78%" height={12} /></View>)}</Card></View>; }
const s = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 8 }, flex: { flex: 1, minWidth: 0 }, badgeCount: { position: "absolute", top: 1, right: 0, minWidth: 20, height: 20, borderRadius: 10, paddingHorizontal: 4, alignItems: "center", justifyContent: "center" }, hero: { gap: 16 }, heroTitle: { flexDirection: "row", alignItems: "center", gap: 12 }, heroIcon: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" }, heroSupport: { flexDirection: "row", gap: 10 }, heroValue: { flex: 1, minWidth: 0, gap: 2 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, metricIcon: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center" }, sectionTitle: { flexDirection: "row", alignItems: "center", gap: 12 }, dataRow: { minHeight: 72, flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 10 }, rowEnd: { maxWidth: "44%", alignItems: "flex-end", gap: 5 }, offline: { minHeight: 40, flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8 } });
