import { useState } from "react";
import { ActivityIndicator, Keyboard, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";
import { Screen } from "@/components/Screen";
import { useTrackOrder, trackingErrorMessage } from "./hooks/useTrackOrder";
import { OrderTrackingCard } from "./components/OrderTrackingCard";
import { useOrderFlowStore } from "@/store/orderFlowStore";
import { theme } from "@/theme";
import { normalizeIndianMobile } from "@/utils/customerValidation";

export default function TrackOrderScreen() {
  const confirmed = useOrderFlowStore((state) => state.confirmedOrder); const savedMobile = useOrderFlowStore((state) => state.trackingMobile);
  const [orderNumber, setOrderNumber] = useState(confirmed?.orderNumber ?? ""); const [mobile, setMobile] = useState(savedMobile); const [errors, setErrors] = useState<{ orderNumber?: string; mobile?: string }>({});
  const lookup = useTrackOrder();
  const track = () => { const normalized = normalizeIndianMobile(mobile); const next = { orderNumber: orderNumber.trim().length < 3 ? "Enter a valid order number." : undefined, mobile: normalized ? undefined : "Enter a valid 10-digit mobile number." }; setErrors(next); if (next.orderNumber || next.mobile || lookup.isPending) return; Keyboard.dismiss(); lookup.mutate({ orderNumber: orderNumber.trim(), mobile: normalized! }); };
  const refresh = () => { const normalized = normalizeIndianMobile(mobile); if (lookup.data && normalized && !lookup.isPending) lookup.mutate({ orderNumber: orderNumber.trim(), mobile: normalized }); };
  return <Screen title="Track Order" subtitle="Enter both details to privately check the latest order status." refreshControl={<RefreshControl refreshing={lookup.isPending && Boolean(lookup.data)} onRefresh={refresh} enabled={Boolean(lookup.data)} />}><View style={styles.card}><Text style={styles.label}>Order number</Text><TextInput accessibilityLabel="Order number" value={orderNumber} onChangeText={(value) => { setOrderNumber(value); lookup.reset(); setErrors({}); }} autoCapitalize="characters" autoCorrect={false} returnKeyType="next" placeholder="Example: MSC-12345" placeholderTextColor={theme.colors.muted} style={styles.input} />{errors.orderNumber ? <Text style={styles.fieldError}>{errors.orderNumber}</Text> : null}<Text style={styles.label}>Customer mobile</Text><TextInput accessibilityLabel="Customer mobile" value={mobile} onChangeText={(value) => { setMobile(value); lookup.reset(); setErrors({}); }} keyboardType="phone-pad" autoComplete="tel" textContentType="telephoneNumber" returnKeyType="done" onSubmitEditing={track} placeholder="10-digit mobile number" placeholderTextColor={theme.colors.muted} style={styles.input} />{errors.mobile ? <Text style={styles.fieldError}>{errors.mobile}</Text> : null}<Pressable accessibilityRole="button" accessibilityLabel="Track Order" accessibilityState={{ disabled: lookup.isPending, busy: lookup.isPending }} disabled={lookup.isPending} onPress={track} style={[styles.button, lookup.isPending && styles.disabled]}>{lookup.isPending && !lookup.data ? <ActivityIndicator color="white" /> : <Text style={styles.buttonText}>{lookup.data ? "Check Latest Status" : "Track Order"}</Text>}</Pressable></View>{lookup.error ? <View accessibilityLiveRegion="polite" style={styles.error}><Text style={styles.errorText}>{trackingErrorMessage(lookup.error)}</Text><Pressable accessibilityRole="button" accessibilityLabel="Retry tracking" onPress={track}><Text style={styles.retry}>Try Again</Text></Pressable></View> : null}{lookup.data ? <OrderTrackingCard order={lookup.data.order} /> : null}</Screen>;
}
const styles = StyleSheet.create({ card: { padding: 16, borderRadius: 16, backgroundColor: theme.colors.surface, ...theme.shadow }, label: { marginTop: 10, marginBottom: 6, fontWeight: "700", color: theme.colors.text }, input: { minHeight: 50, paddingHorizontal: 14, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 10, backgroundColor: theme.colors.background, color: theme.colors.text }, fieldError: { marginTop: 5, color: theme.colors.danger }, button: { minHeight: 52, marginTop: 18, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: theme.colors.primary }, disabled: { opacity: .6 }, buttonText: { color: "white", fontWeight: "800" }, error: { marginTop: 16, padding: 14, borderRadius: 10, backgroundColor: "#FEF2F2" }, errorText: { color: theme.colors.danger }, retry: { marginTop: 10, fontWeight: "800", color: theme.colors.primary } });
