import type {Bill,CustomerDetail,DueCustomer,DueFilters,DueOrder,PaymentHistory,PaymentMode,PaymentStatus} from "./types";const rec=(v:unknown):Record<string,unknown>=>v&&typeof v==="object"?v as Record<string,unknown>:{};const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0};const s=(v:unknown,f="")=>typeof v==="string"?v:f;const nullable=(v:unknown)=>typeof v==="string"&&v.trim()?v:null;const status=(v:unknown):PaymentStatus=>v==="DUE"||v==="PARTIALLY_PAID"||v==="PAID"?v:"UNKNOWN";const mode=(v:unknown):PaymentMode|"UNKNOWN"=>v==="CASH"||v==="ONLINE"?v:"UNKNOWN";
const order=(x:unknown):DueOrder=>{const v=rec(x);return{id:n(v.id),orderNumber:s(v.orderNumber,"Order"),createdAt:s(v.createdAt),finalAmount:n(v.finalAmount),cashPaid:n(v.cashPaid),onlinePaid:n(v.onlinePaid),paid:n(v.paid),due:n(v.due),paymentStatus:status(v.paymentStatus)}};
export function normalizeCustomer(x:unknown):DueCustomer{const v=rec(x);return{customerName:s(v.customerName,"Customer"),customerMobile:s(v.customerMobile),totalOrders:n(v.totalOrders),totalPurchase:n(v.totalPurchase),totalPaid:n(v.totalPaid),totalDue:n(v.totalDue),orders:Array.isArray(v.orders)?v.orders.map(order):[]}}
export function normalizeCustomerDetail(x:unknown):CustomerDetail{const v=rec(x),c=normalizeCustomer(v.customer);return{customer:{customerName:c.customerName,customerMobile:c.customerMobile,totalOrders:c.totalOrders,totalPurchase:c.totalPurchase,totalPaid:c.totalPaid,totalDue:c.totalDue},orders:Array.isArray(v.orders)?v.orders.map(order):[],paymentHistory:Array.isArray(v.paymentHistory)?v.paymentHistory.map(y=>{const p=rec(y);return{id:n(p.id),orderNumber:s(p.orderNumber),amount:n(p.amount),paymentMode:mode(p.paymentMode),paymentDate:s(p.paymentDate),notes:nullable(p.notes),previousDue:n(p.previousDue),remainingDue:n(p.remainingDue)}}):[]}}
export function normalizeBill(x:unknown):Bill|null{if(!x)return null;const v=rec(x);return{id:n(v.id),orderId:n(v.orderId),subtotal:n(v.subtotal),discount:n(v.discount),finalAmount:n(v.finalAmount),createdAt:s(v.createdAt),updatedAt:s(v.updatedAt)}}
export const query=<T extends object>(v:T)=>{const q=new URLSearchParams();Object.entries(v as Record<string,unknown>).forEach(([k,x])=>{if(x!==undefined&&x!=="")q.set(k,String(x))});return q.toString()};
export function paymentError(amount:string,due:number){const x=Number(amount);if(amount.trim()===""||!Number.isFinite(x)||x<=0)return"Enter an amount greater than zero.";if(Math.round(x*100)/100!==x)return"Amount supports up to 2 decimal places.";if(x>due+.001)return"Amount cannot exceed the remaining due.";return null}
export function dateError(value:string){if(!value)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return"Use payment date YYYY-MM-DD.";const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?"Enter a valid payment date.":null}
export function discountError(value:string,subtotal:number){const x=Number(value);if(value.trim()===""||!Number.isFinite(x)||x<0)return"Enter a discount of 0 or more.";if(Math.round(x*100)/100!==x)return"Discount supports up to 2 decimal places.";if(x>subtotal)return"Discount cannot exceed subtotal.";return null}
export const finalPreview=(subtotal:number,discount:string)=>Math.max(0,Math.round((subtotal-(Number(discount)||0))*100)/100);
export const dueQuery=(f:DueFilters)=>query(f);
