export const adminQueryKeys = {
  root: ["admin"] as const,
  session: () => [...adminQueryKeys.root, "session"] as const,
  dashboard: () => [...adminQueryKeys.root, "dashboard", "overview"] as const,
  notifications: (limit = 1) => [...adminQueryKeys.root, "notifications", { limit }] as const,
  notificationList: (unreadOnly: boolean) => [...adminQueryKeys.root, "notifications", "list", { unreadOnly }] as const,
  analytics: () => [...adminQueryKeys.root, "analytics"] as const,
  analyticsBundle: () => [...adminQueryKeys.analytics(), "bundle"] as const,
  chart: (kind: string) => [...adminQueryKeys.analytics(), "chart", kind] as const,
  reports: () => [...adminQueryKeys.root, "reports"] as const,
  settings: () => [...adminQueryKeys.root, "settings"] as const,
  profile: () => [...adminQueryKeys.root, "profile"] as const,
  salesReport: (query: string) => [...adminQueryKeys.reports(), "sales", query] as const,
  orders: () => [...adminQueryKeys.root, "orders"] as const,
  orderList: (filters: object) => [...adminQueryKeys.orders(), "list", filters] as const,
  orderDetail: (id: number) => [...adminQueryKeys.orders(), "detail", id] as const,
  orderProducts: (search: string) => [...adminQueryKeys.orders(), "products", search] as const,
  products: () => [...adminQueryKeys.root, "products"] as const,
  productList: (filters: object) => [...adminQueryKeys.products(), "list", filters] as const,
  productDetail: (id: number) => [...adminQueryKeys.products(), "detail", id] as const,
  categories: () => [...adminQueryKeys.root, "categories"] as const,
  dues: () => [...adminQueryKeys.root, "dues"] as const,
  dueSnapshot: (filters: object) => [...adminQueryKeys.dues(), "snapshot", filters] as const,
  dueCustomer: (mobile: string) => [...adminQueryKeys.dues(), "customer", mobile] as const,
  billing: () => [...adminQueryKeys.root, "billing"] as const,
  bill: (orderId: number) => [...adminQueryKeys.billing(), "order", orderId] as const,
} as const;

// Business query hooks are intentionally deferred to their implementation phases.
