import type { SalesPeriod } from "./types";
export function isoDate(date=new Date()){return date.toISOString().slice(0,10)}
export function validIsoDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const [year,month,day]=value.split("-").map(Number),date=new Date(Date.UTC(year,month-1,day));return date.getUTCFullYear()===year&&date.getUTCMonth()===month-1&&date.getUTCDate()===day}
export function datePickerValue(value:string,fallback=new Date()){if(!validIsoDate(value.trim()))return fallback;const[year,month,day]=value.trim().split("-").map(Number);return new Date(year,month-1,day,12)}
export function dateFromPicker(current:string,selected?:Date){if(!selected)return current;const year=selected.getFullYear(),month=String(selected.getMonth()+1).padStart(2,"0"),day=String(selected.getDate()).padStart(2,"0");return`${year}-${month}-${day}`}
export function monthYearFromPicker(month:string,year:string,selected?:Date){return selected?{month:String(selected.getMonth()+1),year:String(selected.getFullYear())}:{month,year}}
export function validateSalesPeriod(period:SalesPeriod,date:string,from:string,to:string,month:string,year:string){if(period==="daily")return validIsoDate(date.trim())?null:"Enter a valid date as YYYY-MM-DD.";if(period==="weekly"){if(!validIsoDate(from.trim())||!validIsoDate(to.trim()))return"Enter valid From and To dates as YYYY-MM-DD.";if(from.trim()>to.trim())return"From date must be on or before To date.";return null}const m=Number(month),y=Number(year);if(!Number.isInteger(m)||m<1||m>12)return"Month must be a number from 1 to 12.";if(!/^\d{4}$/.test(year.trim())||!Number.isInteger(y))return"Year must contain four digits.";return null}
export function salesPeriodQuery(period:SalesPeriod, date:string, from:string, to:string, month:string, year:string){const q=new URLSearchParams({type:period});if(period==="daily")q.set("date",date.trim());if(period==="weekly"){q.set("from",from.trim());q.set("to",to.trim())}if(period==="monthly"){q.set("month",String(Number(month)));q.set("year",year.trim())}return q.toString()}
export function safeExportName(period:SalesPeriod,ext:"csv"|"xlsx",stamp=new Date()){return `sales-report-${period}-${stamp.toISOString().slice(0,10)}.${ext}`}
export function notificationCopy(n:{title?:string;message?:string;orderNumber:string;customerName:string;status:string}){return{title:n.title||`New order ${n.orderNumber}`,message:n.message||`${n.customerName} placed an order · ${n.status.replaceAll("_"," ")}`}}
