import type { ChartPoint, Dict, NotificationItem, NotificationPage, ReportPayment, SalesReport } from "./types";
const obj=(v:unknown):Dict=>v!==null&&typeof v==="object"&&!Array.isArray(v)?v as Dict:{};
const arr=(v:unknown):unknown[]=>Array.isArray(v)?v:[];
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const str=(v:unknown)=>typeof v==="string"?v:"";
export const normalizeNotificationPage=(v:unknown):NotificationPage=>{const r=obj(v);return{notifications:arr(r.notifications).map((x):NotificationItem=>{const n=obj(x),orderId=num(n.orderId),productId=num(n.productId);return{id:num(n.id),type:str(n.type)||"NEW_ORDER",title:str(n.title),message:str(n.message),orderId:orderId||null,productId:productId||null,orderNumber:str(n.orderNumber),customerName:str(n.customerName),status:str(n.status),read:n.read===true,createdAt:str(n.createdAt)||null}}),total:num(r.total),unreadCount:num(r.unreadCount)}};
export const normalizeSalesReport=(v:unknown):SalesReport=>{const report=obj(obj(v).report);const mapPayment=(x:unknown):ReportPayment=>{const p=obj(x);const originalBill=num(p.originalBillAmount);const paidBeforePayment=num(p.previouslyPaidBeforePayment);const dueBefore=num(p.dueBeforePayment)||Math.max(0,originalBill-paidBeforePayment);return{id:num(p.id),orderNumber:str(p.orderNumber),customerName:str(p.customerName),customerMobile:str(p.customerMobile),orderCreatedAt:str(p.orderCreatedAt),subtotal:num(p.subtotal),originalBillAmount:originalBill,paymentDate:str(p.paymentDate),amount:num(p.amount),paymentMode:str(p.paymentMode)||"CASH",previouslyPaidBeforePeriod:num(p.previouslyPaidBeforePeriod),previouslyPaidBeforePayment:paidBeforePayment,dueBeforePayment:dueBefore,totalPaidAfterPayment:num(p.totalPaidAfterPayment),remainingBalanceAfterPayment:num(p.remainingBalanceAfterPayment),paymentStatusAfterPayment:str(p.paymentStatusAfterPayment),saleCreatedInPeriod:p.saleCreatedInPeriod===true,salePeriodType:(str(p.salePeriodType)||"OLDER_SALE_PREVIOUS_DUE") as "CURRENT_PERIOD_SALE"|"OLDER_SALE_PREVIOUS_DUE",dueCleared:p.dueCleared===true,dueClearedAmount:p.dueClearedAmount==null?null:num(p.dueClearedAmount),dueClearedAt:str(p.dueClearedAt)||null}};const payments=arr(report.payments).map(mapPayment);const previousDuePayments=arr(report.previousDuePayments).length?arr(report.previousDuePayments).map(mapPayment):payments.filter(p=>!p.saleCreatedInPeriod);return{reportType:(str(report.reportType)||"daily") as SalesReport["reportType"],periodLabel:str(report.periodLabel),generatedAt:str(report.generatedAt),generatedBy:str(report.generatedBy),summary:obj(report.summary),collections:obj(report.collections),orders:arr(report.orders).map(x=>{const o=obj(x);return{id:num(o.id),orderNumber:str(o.orderNumber),customerName:str(o.customerName),customerMobile:str(o.customerMobile),createdAt:str(o.createdAt),status:str(o.status),finalAmount:num(o.finalAmount),totalPaid:num(o.totalPaid),remainingDue:num(o.remainingDue),paymentStatus:str(o.paymentStatus)}}),payments,previousDuePayments}};
export const normalizePoints=(v:unknown):ChartPoint[]=>arr(obj(v).points).map((x,i)=>{const p=obj(x);return{label:str(p.name)||str(p.date)||str(p.week)||str(p.month)||`Point ${i+1}`,value:num(p.value??p.sales??p.due)}});
export const asObject=obj; export const asArray=arr; export const asNumber=num; export const asString=str;
