import { forwardRef, memo, useState, type ReactNode } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, TextInput, View, type PressableProps, type TextInputProps, type ViewProps } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { AppText } from "./AppText";
import { useTheme } from "@/theme";
export function Card({ children, style, elevated = true, ...props }: ViewProps & { elevated?: boolean }) { const t = useTheme(); return <View {...props} style={[s.card, { padding: t.spacing.lg, borderRadius: t.radius.large, borderColor: t.colors.border, backgroundColor: t.colors.surface, shadowColor: t.colors.shadow }, elevated && t.elevation.card, style]}>{children}</View>; }
type Variant = "primary" | "secondary" | "outline" | "ghost" | "danger";
export function Button({ title, variant = "primary", loading = false, disabled, leftIcon, style, ...props }: PressableProps & { title: string; variant?: Variant; loading?: boolean; leftIcon?: ReactNode }) { const t = useTheme(); const p = variant === "danger" ? [t.colors.danger, t.colors.textInverse] : variant === "primary" ? [t.colors.brand, t.colors.brandForeground] : variant === "secondary" ? [t.colors.brandSoft, t.colors.brand] : ["transparent", variant === "ghost" ? t.colors.brand : t.colors.text]; return <Pressable accessibilityRole="button" accessibilityState={{ disabled: !!disabled, busy: loading }} disabled={disabled || loading} android_ripple={{ color: t.colors.surfaceInteractive }} {...props} style={({ pressed }) => [s.button, { backgroundColor: p[0], borderColor: variant === "outline" ? t.colors.borderStrong : p[0], borderRadius: t.radius.medium, opacity: disabled ? .48 : pressed ? .82 : 1 }, style as never]}>{loading ? <ActivityIndicator color={p[1]} /> : leftIcon}<AppText role="button" style={{ color: p[1], opacity: loading ? 0 : 1 }}>{title}</AppText></Pressable>; }
export function IconButton({ icon, label, ...props }: PressableProps & { icon: keyof typeof Ionicons.glyphMap; label: string }) { const t = useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={label} hitSlop={4} android_ripple={{ color: t.colors.surfaceInteractive, borderless: true }} {...props} style={({ pressed }) => [s.iconButton, { borderRadius: t.radius.pill, opacity: pressed ? .7 : 1 }]}><Ionicons name={icon} size={22} color={t.colors.text} /></Pressable>; }
export const Input = forwardRef<TextInput, TextInputProps & { label?: string; required?: boolean; helper?: string; error?: string; prefix?: ReactNode; suffix?: ReactNode; disabled?: boolean }>(function Input({ label, required, helper, error, prefix, suffix, disabled, style, ...props }, ref) { const t = useTheme(); const [focused, setFocused] = useState(false); return <View style={s.field}>{label && <AppText role="label">{label}{required && <AppText role="label" style={{ color: t.colors.danger }}> *</AppText>}</AppText>}<View style={[s.inputWrap, { minHeight: props.multiline ? 104 : 50, borderRadius: t.radius.medium, borderColor: error ? t.colors.danger : focused ? t.colors.brand : t.colors.inputBorder, backgroundColor: disabled ? t.colors.surfaceMuted : t.colors.inputBackground }]}>{prefix}<TextInput ref={ref} accessibilityState={{ disabled: !!disabled }} editable={!disabled} placeholderTextColor={t.colors.placeholder} {...props} onFocus={e => { setFocused(true); props.onFocus?.(e); }} onBlur={e => { setFocused(false); props.onBlur?.(e); }} style={[s.input, { color: t.colors.text, textAlignVertical: props.multiline ? "top" : "center" }, style]} />{suffix}</View>{(error || helper) && <AppText role="caption" style={{ color: error ? t.colors.danger : t.colors.textMuted }}>{error || helper}</AppText>}</View>; });
export function SearchInput(props: Omit<React.ComponentProps<typeof Input>, "prefix">) { const t = useTheme(); return <Input accessibilityLabel="Search" returnKeyType="search" prefix={<Ionicons name="search" size={20} color={t.colors.textMuted} />} {...props} />; }
export const FormField = Input;
export function SectionHeader({ title, action }: { title: string; action?: ReactNode }) { return <View style={s.between}><AppText role="sectionTitle" style={s.flex}>{title}</AppText>{action}</View>; }
export function Divider() { const t = useTheme(); return <View style={[s.divider, { backgroundColor: t.colors.divider }]} />; }
type Tone = "neutral" | "success" | "warning" | "danger" | "info";
export function StatusBadge({ label, tone = "neutral", icon = "ellipse" }: { label: string; tone?: Tone; icon?: keyof typeof Ionicons.glyphMap }) { const t = useTheme(); const fg = tone === "success" ? t.colors.success : tone === "warning" ? t.colors.warning : tone === "danger" ? t.colors.danger : tone === "info" ? t.colors.info : t.colors.textSecondary; const bg = tone === "success" ? t.colors.successSoft : tone === "warning" ? t.colors.warningSoft : tone === "danger" ? t.colors.dangerSoft : tone === "info" ? t.colors.infoSoft : t.colors.surfaceMuted; return <View accessibilityLabel={`Status: ${label}`} style={[s.badge, { borderRadius: t.radius.pill, backgroundColor: bg }]}><Ionicons name={icon} size={12} color={fg} /><AppText role="status" style={{ color: fg }}>{label}</AppText></View>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { const t = useTheme(); return <View style={s.state}><Ionicons name="file-tray-outline" size={30} color={t.colors.textMuted} /><AppText role="cardTitle">{title}</AppText><AppText style={[s.center, { color: t.colors.textSecondary }]}>{description}</AppText>{action}</View>; }
export function ErrorState({ title = "Could not load data", description, onRetry }: { title?: string; description: string; onRetry?: () => void }) { const t = useTheme(); return <View style={s.state}><Ionicons name="alert-circle-outline" size={30} color={t.colors.danger} /><AppText role="cardTitle">{title}</AppText><AppText style={[s.center, { color: t.colors.textSecondary }]}>{description}</AppText>{onRetry && <Button title="Try again" variant="outline" onPress={onRetry} />}</View>; }
export function LoadingState({ label = "Loading" }: { label?: string }) { const t = useTheme(); return <View accessibilityRole="progressbar" style={s.state}><ActivityIndicator color={t.colors.brand} /><AppText style={{ color: t.colors.textSecondary }}>{label}</AppText></View>; }
export function Skeleton({ width = "100%", height = 16, radius }: { width?: number | `${number}%`; height?: number; radius?: number }) { const t = useTheme(); return <View accessibilityElementsHidden style={{ width, height, borderRadius: radius ?? t.radius.small, backgroundColor: t.colors.skeleton }} />; }
export function CardSkeleton() { const t = useTheme(); return <Card><View style={{ gap: t.spacing.md }}><Skeleton width="48%" /><Skeleton height={30} width="70%" /><Skeleton /></View></Card>; }
export function ListRowSkeleton() { const t = useTheme(); return <View style={[s.row, { gap: t.spacing.md }]}><Skeleton width={42} height={42} radius={21} /><View style={[s.flex, { gap: t.spacing.sm }]}><Skeleton width="54%" /><Skeleton width="76%" height={12} /></View></View>; }
export const ListRow = memo(function ListRow({ title, subtitle, leading, trailing, onPress }: { title: string; subtitle?: string; leading?: ReactNode; trailing?: ReactNode; onPress?: () => void }) { const t = useTheme(); const content = <><View>{leading}</View><View style={s.flex}><AppText role="bodyStrong" numberOfLines={1}>{title}</AppText>{subtitle && <AppText role="caption" numberOfLines={2} style={{ color: t.colors.textSecondary }}>{subtitle}</AppText>}</View>{trailing}</>; return onPress ? <Pressable accessibilityRole="button" onPress={onPress} android_ripple={{ color: t.colors.surfaceInteractive }} style={s.row}>{content}</Pressable> : <View style={s.row}>{content}</View>; });
export function MetricCard({ label, value, caption, tone = "brand" }: { label: string; value: string; caption?: string; tone?: "brand" | "success" | "warning" | "danger" }) { const t = useTheme(); const color = tone === "success" ? t.colors.success : tone === "warning" ? t.colors.warning : tone === "danger" ? t.colors.danger : t.colors.brand; return <Card style={s.metric}><AppText role="caption" style={{ color: t.colors.textSecondary }}>{label}</AppText><AppText role="financialValue" adjustsFontSizeToFit numberOfLines={1} style={{ color }}>{value}</AppText>{caption && <AppText role="caption" style={{ color: t.colors.textMuted }}>{caption}</AppText>}</Card>; }
export function FilterChip({ label, selected, onPress }: { label: string; selected?: boolean; onPress?: () => void }) { const t = useTheme(); return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={({ pressed }) => [s.chip, { borderRadius: t.radius.pill, borderColor: selected ? t.colors.brand : t.colors.border, backgroundColor: selected ? t.colors.brandSoft : t.colors.surface, opacity: pressed ? .75 : 1 }]}><AppText role="label" style={{ color: selected ? t.colors.brand : t.colors.textSecondary }}>{label}</AppText></Pressable>; }
export function SegmentedControl<T extends string>({ options, value, onChange }: { options: readonly T[]; value: T; onChange: (value: T) => void }) { const t = useTheme(); return <View style={[s.segmented, { borderRadius: t.radius.medium, backgroundColor: t.colors.surfaceMuted }]}>{options.map(option => <Pressable key={option} accessibilityRole="button" accessibilityState={{ selected: value === option }} onPress={() => onChange(option)} style={[s.segment, { borderRadius: t.radius.small, backgroundColor: value === option ? t.colors.surfaceElevated : "transparent" }, value === option && t.elevation.subtle]}><AppText role="label" style={{ color: value === option ? t.colors.text : t.colors.textMuted, textTransform: "capitalize" }}>{option}</AppText></Pressable>)}</View>; }
export function ModalShell({ visible, onClose, title, children }: { visible: boolean; onClose: () => void; title: string; children: ReactNode }) { const t = useTheme(); return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable accessibilityLabel="Close dialog" style={[s.overlay, { backgroundColor: t.colors.overlay }]} onPress={onClose}><Pressable accessibilityViewIsModal style={[s.modal, { maxHeight: "90%", borderRadius: t.radius.xl, backgroundColor: t.colors.surfaceElevated, shadowColor: t.colors.shadow }, t.elevation.floating]} onPress={e => e.stopPropagation()}><View style={s.between}><AppText role="sectionTitle" style={s.flex}>{title}</AppText><IconButton icon="close" label="Close" onPress={onClose} /></View><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={{ gap: 16 }}>{children}</ScrollView></Pressable></Pressable></Modal>; }
export function ConfirmDialog({ visible, title, description, confirmLabel, onCancel, onConfirm, danger = true }: { visible: boolean; title: string; description: string; confirmLabel: string; onCancel: () => void; onConfirm: () => void; danger?: boolean }) { const t = useTheme(); return <ModalShell visible={visible} onClose={onCancel} title={title}><AppText style={{ color: t.colors.textSecondary }}>{description}</AppText><View style={s.actions}><Button title="Cancel" variant="outline" onPress={onCancel} style={s.flex} /><Button title={confirmLabel} variant={danger ? "danger" : "primary"} onPress={onConfirm} style={s.flex} /></View></ModalShell>; }
const s = StyleSheet.create({ card: { borderWidth: 1 }, button: { minHeight: 48, paddingHorizontal: 18, flexDirection: "row", gap: 9, alignItems: "center", justifyContent: "center", borderWidth: 1 }, iconButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center", overflow: "hidden" }, field: { gap: 6 }, inputWrap: { borderWidth: 1.3, flexDirection: "row", gap: 8, alignItems: "center", paddingHorizontal: 13 }, input: { flex: 1, minHeight: 48, paddingVertical: 10, fontSize: 15 }, between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, flex: { flex: 1 }, divider: { height: StyleSheet.hairlineWidth, width: "100%" }, badge: { minHeight: 28, paddingHorizontal: 9, flexDirection: "row", gap: 5, alignItems: "center", alignSelf: "flex-start" }, state: { paddingVertical: 24, paddingHorizontal: 16, alignItems: "center", gap: 8 }, center: { textAlign: "center", maxWidth: 290 }, row: { minHeight: 60, flexDirection: "row", gap: 12, alignItems: "center", paddingVertical: 8 }, metric: { minWidth: 145, flex: 1, gap: 6 }, chip: { minHeight: 40, justifyContent: "center", paddingHorizontal: 14, borderWidth: 1 }, segmented: { padding: 4, flexDirection: "row" }, segment: { minHeight: 40, flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 8 }, overlay: { flex: 1, justifyContent: "center", padding: 20 }, modal: { width: "100%", maxWidth: 440, alignSelf: "center", padding: 20, gap: 16 }, actions: { flexDirection: "row", gap: 12 } });
