import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import type { Category } from "@/types/domain";
import type { ProductSort } from "@/types/api";
import { ProductToolbar } from "./ProductToolbar";
import { theme } from "@/theme";

export function CatalogueHeader({ title = "Products", subtitle, categories, category, onCategory, sort, inStock, onSort, onInStock, showSearch = true }: { title?: string; subtitle?: string; categories?: Category[]; category?: string; onCategory?: (slug?: string) => void; sort: ProductSort; inStock: boolean; onSort: (sort: ProductSort) => void; onInStock: (value: boolean) => void; showSearch?: boolean }) {
  const router = useRouter();
  return <View style={styles.header}><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}{showSearch ? <Pressable accessibilityRole="search" accessibilityLabel="Search products" onPress={() => router.push("/search")} style={styles.search}><Text style={styles.searchIcon}>⌕</Text><Text style={styles.searchText}>Search cement, steel, roofing sheets…</Text><Text style={styles.arrow}>›</Text></Pressable> : null}{categories?.length && onCategory ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><Pressable accessibilityRole="button" onPress={() => onCategory(undefined)} style={[styles.chip, !category && styles.chipActive]}><Text style={[styles.chipText, !category && styles.chipTextActive]}>All</Text></Pressable>{categories.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityState={{ selected: category === item.slug }} onPress={() => onCategory(item.slug)} style={[styles.chip, category === item.slug && styles.chipActive]}><Text style={[styles.chipText, category === item.slug && styles.chipTextActive]}>{item.name}</Text></Pressable>)}</ScrollView> : null}<ProductToolbar sort={sort} inStock={inStock} onSort={onSort} onInStock={onInStock} /></View>;
}
const styles = StyleSheet.create({ header: { paddingTop: 4, paddingBottom: 6 }, title: { fontSize: 28, fontWeight: "900", color: theme.colors.text }, subtitle: { marginTop: 4, color: theme.colors.muted }, search: { minHeight: 54, marginTop: 15, flexDirection: "row", alignItems: "center", gap: 9, paddingHorizontal: 13, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 15, backgroundColor: theme.colors.surface }, searchIcon: { color: theme.colors.primary, fontSize: 25 }, searchText: { flex: 1, color: theme.colors.muted, fontSize: 13 }, arrow: { color: theme.colors.muted, fontSize: 24 }, chips: { gap: 8, paddingTop: 13, paddingRight: 14 }, chip: { minHeight: 42, justifyContent: "center", paddingHorizontal: 14, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 21, backgroundColor: theme.colors.surface }, chipActive: { borderColor: theme.colors.primary, backgroundColor: theme.colors.primary }, chipText: { color: theme.colors.text, fontWeight: "700" }, chipTextActive: { color: "white" } });
