import { useCallback, type ReactElement } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, View, type ListRenderItem } from "react-native";
import { ProductCard } from "@/components/ProductCard";
import { ProductSkeleton } from "@/components/ProductSkeleton";
import type { Product } from "@/types/domain";
import { theme } from "@/theme";

export function ProductGrid({ products, total, loading, error, refreshing, fetchingNext, hasNext, onRefresh, onRetry, onEndReached, onAdd, header, emptyMessage }: { products: Product[]; total: number; loading: boolean; error: boolean; refreshing: boolean; fetchingNext: boolean; hasNext: boolean; onRefresh: () => void; onRetry: () => void; onEndReached: () => void; onAdd: (product: Product) => void; header: ReactElement; emptyMessage: string }) {
  const renderProduct = useCallback<ListRenderItem<Product>>(({ item }) => <ProductCard product={item} onAdd={() => onAdd(item)} style={styles.card} />, [onAdd]);
  if (loading && !products.length) return <FlatList data={[1, 2, 3, 4, 5, 6]} keyExtractor={String} numColumns={2} renderItem={() => <ProductSkeleton />} columnWrapperStyle={styles.columns} ListHeaderComponent={header} contentContainerStyle={styles.content} />;
  return <FlatList data={products} keyExtractor={(item) => String(item.id)} numColumns={2} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" renderItem={renderProduct} columnWrapperStyle={styles.columns} ListHeaderComponent={<>{header}{products.length ? <Text style={styles.count}>{total} product{total === 1 ? "" : "s"}</Text> : null}</>} ListEmptyComponent={error ? <Pressable accessibilityRole="button" onPress={onRetry} style={styles.state}><Text style={styles.errorTitle}>Couldn't load products.</Text><Text style={styles.retry}>Check your connection and tap to retry.</Text></Pressable> : <View style={styles.state}><Text style={styles.emptyTitle}>{emptyMessage}</Text></View>} ListFooterComponent={fetchingNext ? <ActivityIndicator style={styles.footer} color={theme.colors.primary} /> : null} onEndReached={() => { if (hasNext && !fetchingNext) onEndReached(); }} onEndReachedThreshold={0.45} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} colors={[theme.colors.primary]} tintColor={theme.colors.primary} />} contentContainerStyle={styles.content} removeClippedSubviews initialNumToRender={8} maxToRenderPerBatch={8} windowSize={7} />;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 110, flexGrow: 1 }, columns: { justifyContent: "space-between", gap: 10, marginBottom: 12 }, card: { flex: 1, width: undefined, maxWidth: "49%" }, count: { marginVertical: 12, color: theme.colors.muted, fontSize: 12, fontWeight: "600" }, state: { minHeight: 220, alignItems: "center", justifyContent: "center", padding: 24 }, errorTitle: { color: theme.colors.danger, fontSize: 18, fontWeight: "800" }, retry: { marginTop: 8, textAlign: "center", color: theme.colors.primary, fontWeight: "700" }, emptyTitle: { textAlign: "center", color: theme.colors.muted, fontSize: 16 }, footer: { paddingVertical: 22 } });
