import { Modal, Pressable, StyleSheet, Switch, Text, View } from "react-native";
import { useState } from "react";
import type { ProductSort } from "@/types/api";
import { theme } from "@/theme";

export const SORT_LABELS: Record<ProductSort, string> = { newest: "Newest", price_asc: "Price: Low to High", price_desc: "Price: High to Low", name_asc: "Name: A to Z", name_desc: "Name: Z to A" };
const sortValues = Object.keys(SORT_LABELS) as ProductSort[];

export function ProductToolbar({ sort, inStock, onSort, onInStock }: { sort: ProductSort; inStock: boolean; onSort: (sort: ProductSort) => void; onInStock: (value: boolean) => void }) {
  const [open, setOpen] = useState(false);
  return <View style={styles.toolbar}><Pressable accessibilityRole="button" accessibilityLabel={`Sort products, current ${SORT_LABELS[sort]}`} onPress={() => setOpen(true)} style={styles.control}><Text style={styles.controlText}>⇅  {SORT_LABELS[sort]}</Text></Pressable><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: inStock }} onPress={() => onInStock(!inStock)} style={[styles.control, inStock && styles.active]}><Text style={[styles.controlText, inStock && styles.activeText]}>✓  In stock</Text></Pressable>
    <Modal visible={open} transparent animationType="slide" onRequestClose={() => setOpen(false)}><Pressable style={styles.backdrop} onPress={() => setOpen(false)}><Pressable style={styles.sheet} onPress={(event) => event.stopPropagation()}><View style={styles.handle} /><Text style={styles.title}>Sort products</Text>{sortValues.map((value) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ checked: sort === value }} onPress={() => { onSort(value); setOpen(false); }} style={styles.option}><Text style={[styles.optionText, sort === value && styles.selected]}>{SORT_LABELS[value]}</Text><View style={[styles.radio, sort === value && styles.radioSelected]} /></Pressable>)}<View style={styles.filterRow}><View><Text style={styles.optionText}>In-stock products only</Text><Text style={styles.hint}>Uses current public stock data</Text></View><Switch value={inStock} onValueChange={onInStock} trackColor={{ true: theme.colors.primary }} /></View></Pressable></Pressable></Modal>
  </View>;
}
const styles = StyleSheet.create({ toolbar: { marginTop: 13, flexDirection: "row", flexWrap: "wrap", gap: 8 }, control: { minHeight: 44, justifyContent: "center", paddingHorizontal: 12, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 12, backgroundColor: theme.colors.surface }, active: { borderColor: theme.colors.primary, backgroundColor: "#ECFDF5" }, controlText: { color: theme.colors.text, fontSize: 12, fontWeight: "700" }, activeText: { color: theme.colors.primaryDark }, backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15,23,42,0.45)" }, sheet: { padding: 20, paddingBottom: 34, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: theme.colors.surface }, handle: { width: 42, height: 4, alignSelf: "center", borderRadius: 2, backgroundColor: theme.colors.border }, title: { marginVertical: 18, fontSize: 21, fontWeight: "900", color: theme.colors.text }, option: { minHeight: 52, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border }, optionText: { color: theme.colors.text, fontWeight: "700" }, selected: { color: theme.colors.primary }, radio: { width: 20, height: 20, borderWidth: 2, borderColor: theme.colors.border, borderRadius: 10 }, radioSelected: { borderWidth: 6, borderColor: theme.colors.primary }, filterRow: { minHeight: 66, marginTop: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, hint: { marginTop: 3, color: theme.colors.muted, fontSize: 11 } });
