import { Prisma } from "@prisma/client";
import { prisma } from "../db.js";

export type NotificationType="NEW_ORDER"|"LOW_STOCK"|"OUT_OF_STOCK"|"PAYMENT_RECEIVED";
export interface NotificationEvent {adminId:number;type:NotificationType;title:string;message:string;orderId?:number;orderNumber?:string;customerName?:string;productId?:number;metadata?:Record<string,unknown>;dedupeKey?:string}
const EXPO_ENDPOINT="https://exp.host/--/api/v2/push/send";
export const isExpoPushToken=(value:unknown):value is string=>typeof value==="string"&&/^ExponentPushToken\[[A-Za-z0-9_-]+\]$|^ExpoPushToken\[[A-Za-z0-9_-]+\]$/.test(value);
export function stockTransition(previous:number,next:number,threshold:number):"LOW_STOCK"|"OUT_OF_STOCK"|null{if(previous>0&&next<=0)return"OUT_OF_STOCK";if(previous>threshold&&next>0&&next<=threshold)return"LOW_STOCK";return null}

async function dispatchPush(event:NotificationEvent,notificationId:number){const devices=await prisma.adminPushDevice.findMany({where:{adminId:event.adminId,isActive:true},select:{id:true,expoPushToken:true}});if(!devices.length)return;const messages=devices.map(d=>({to:d.expoPushToken,sound:"default",channelId:event.type==="NEW_ORDER"?"orders":event.type==="PAYMENT_RECEIVED"?"payments":"inventory",title:event.title,body:event.message,data:{notificationId,type:event.type,orderId:event.orderId,productId:event.productId}}));try{const response=await fetch(EXPO_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(messages)});if(!response.ok)throw new Error(`Expo push HTTP ${response.status}`);const payload=await response.json() as {data?:Array<{status?:string;details?:{error?:string}}>};const dead=devices.filter((_,i)=>payload.data?.[i]?.details?.error==="DeviceNotRegistered").map(d=>d.id);if(dead.length)await prisma.adminPushDevice.updateMany({where:{id:{in:dead}},data:{isActive:false}})}catch(error){console.error("[push] Delivery failed",error instanceof Error?error.message:"Unknown provider failure")}}

export async function createAdminNotification(event:NotificationEvent){try{const notification=await prisma.notification.create({data:{adminId:event.adminId,type:event.type,title:event.title,message:event.message,orderId:event.orderId,orderNumber:event.orderNumber,customerName:event.customerName,productId:event.productId,metadata:event.metadata as Prisma.InputJsonValue|undefined,dedupeKey:event.dedupeKey}});void dispatchPush(event,notification.id);return notification}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")return null;throw error}}

export async function notifyStockTransitions(changes:Array<{productId:number;name:string;previous:number;next:number}>,operationKey:string){const admins=await prisma.admin.findMany({where:{isActive:true},select:{id:true,profile:{select:{lowStockThreshold:true}}}});for(const admin of admins){const threshold=admin.profile?.lowStockThreshold??10;for(const change of changes){const type=stockTransition(change.previous,change.next,threshold);if(!type)continue;await createAdminNotification({adminId:admin.id,type,productId:change.productId,title:type==="OUT_OF_STOCK"?"Product out of stock":"Low stock alert",message:`${change.name}: ${change.next} remaining`,metadata:{stock:change.next,threshold},dedupeKey:`${type}:${change.productId}:${operationKey}`})}}}
