import type { Category, Product, ProductPage } from "./types";
import { environment } from "@/config/environment";
const rec=(v:unknown):Record<string,unknown>=>v&&typeof v==="object"?v as Record<string,unknown>:{};const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0};const s=(v:unknown,f="")=>typeof v==="string"?v:f;const nullable=(v:unknown)=>typeof v==="string"&&v.trim()?v:null;
export function normalizeCategory(value:unknown):Category{const v=rec(value);return{id:n(v.id),name:s(v.name,"Unnamed category"),slug:s(v.slug),imageUrl:nullable(v.imageUrl),displayOrder:n(v.displayOrder),isActive:v.isActive===true,...(v.productCount===undefined?{}:{productCount:n(v.productCount)})}}
export function normalizeProduct(value:unknown):Product{const v=rec(value),c=rec(v.category);return{id:n(v.id),name:s(v.name,"Unnamed product"),description:nullable(v.description),unit:s(v.unit),price:n(v.price),mrp:n(v.mrp),stock:n(v.stock),isActive:v.isActive===true,categoryId:n(v.categoryId),category:v.category?{id:n(c.id),name:s(c.name,"Uncategorized"),slug:s(c.slug)}:null,imageUrl:nullable(v.imageUrl),images:Array.isArray(v.images)?v.images.map(x=>{const i=rec(x);return{id:n(i.id),url:s(i.url),alt:nullable(i.alt),isPrimary:i.isPrimary===true}}):[],createdAt:s(v.createdAt),updatedAt:s(v.updatedAt)}}
export function normalizeProductPage(value:unknown):ProductPage{const v=rec(value);return{products:Array.isArray(v.products)?v.products.map(normalizeProduct):[],total:n(v.total),page:Math.max(1,n(v.page)||1),pages:Math.max(1,n(v.pages)||1)}}
export const serializeProductQuery=(v:Record<string,string|number|undefined>)=>{const q=new URLSearchParams();Object.entries(v).forEach(([k,x])=>{if(x===undefined||x===""||(k==="categoryId"&&x===0))return;q.set(k,String(x))});return q.toString()};
export function mergeProducts<T extends{id:number}>(pages:T[][]){const ids=new Set<number>();return pages.flatMap(p=>p.filter(x=>x.id>0&&!ids.has(x.id)&&!!ids.add(x.id)))}
export const wholeUnit=(unit:string)=>["bag","piece"].includes(unit.trim().toLowerCase());
export function validateQuantity(value:string,unit:string){const x=Number(value);if(value.trim()===""||!Number.isFinite(x)||x<0)return"Enter a stock value of 0 or more.";if(wholeUnit(unit)&&!Number.isInteger(x))return`${unit} stock must be a whole number.`;if(Math.round(x*1000)/1000!==x)return"Stock supports up to 3 decimal places.";return null}
export function validateMoney(value:string,label:string){const x=Number(value);return value.trim()===""||!Number.isFinite(x)||x<0?`Enter a valid ${label} of 0 or more.`:null}
export function stockState(stock:number,threshold:number|null){return stock<=0?{label:"Out of stock",tone:"danger" as const}:threshold===null?{label:"Current stock",tone:"neutral" as const}:stock<=threshold?{label:"Low stock",tone:"warning" as const}:{label:"In stock",tone:"success" as const}}
export function resolveImageUrl(url:string|null){if(!url)return null;if(/^https?:\/\//i.test(url))return url;return `${environment.apiBaseUrl.replace(/\/api$/,"")}${url.startsWith("/")?url:`/${url}`}`}
