import { useEffect, useState } from "react";
import { Redirect, router, useLocalSearchParams } from "expo-router";
import { AppText } from "@/components/AppText";
import { Screen } from "@/components/Screen";
import { Button } from "@/components/ui";
import { AuthFrame } from "@/features/auth/AuthFrame";
import { PasswordField } from "@/features/auth/PasswordField";
import { useAuth } from "@/features/auth/AuthProvider";
import { authErrorMessage, validateResetPassword } from "@/features/auth/authMessages";
import { authService } from "@/features/auth/authService";
import { useTheme } from "@/theme";
export default function ResetPasswordScreen() { const t = useTheme(); const { status } = useAuth(); const { token: rawToken } = useLocalSearchParams<{ token?: string | string[] }>(); const token = Array.isArray(rawToken) ? rawToken[0] : rawToken; const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); useEffect(() => () => { setPassword(""); setConfirmation(""); }, []); if (status === "authenticated") return <Redirect href="/(admin)" />; const submit = async () => { const validation = validateResetPassword(password, confirmation); if (validation) { setError(validation); return; } if (!token) { setError("Reset token is missing. Open the reset link or request a new one."); return; } setLoading(true); setError(null); try { await authService.resetPassword(token, password); setPassword(""); setConfirmation(""); router.replace({ pathname: "/(auth)", params: { reset: "success" } }); } catch (cause) { setError(authErrorMessage(cause, "reset")); } finally { setLoading(false); } }; return <Screen keyboardAware centered contentStyle={{ paddingVertical: t.spacing.xxl }}><AuthFrame title="Reset password" subtitle="Choose a new password between 12 and 128 characters.">{!token && <AppText style={{ color: t.colors.warning }}>No reset token was provided. You can paste a reset link into the app during development or request a new email.</AppText>}{error && <AppText accessibilityRole="alert" style={{ color: t.colors.danger }}>{error}</AppText>}<PasswordField label="New password" required accessibilityLabel="New password" autoComplete="new-password" textContentType="newPassword" value={password} onChangeText={setPassword} placeholder="12–128 characters" /><PasswordField label="Confirm password" required accessibilityLabel="Confirm new password" autoComplete="new-password" textContentType="newPassword" returnKeyType="done" onSubmitEditing={() => void submit()} value={confirmation} onChangeText={setConfirmation} placeholder="Repeat new password" /><Button title="Reset Password" loading={loading} disabled={loading || !token} onPress={() => void submit()} /><Button title="Back to Sign In" variant="ghost" onPress={() => router.replace("/(auth)")} /></AuthFrame></Screen>; }
